### ISSUE TITLE
3 instances, different VIN but same data

### ISSUE THREAD

**Issue by NicoStaehle** [Newan/ioBroker.bluelink#15]
Moin!
Ich habe 3 Instanzen installiert und in jeder eine andere VIN hinterlegt.
Wenn ich auf die Daten der unterschiedlichen Instanzen zugreife erhalte ich jedoch immer die Daten des gleichen Fahrzeuges. (Die Daten stammen von dem Fahrzeug dessen Instanz zu erst gestartet wurde)
Gibt es eine Möglichkeit mehrere Fahrzeuge zu nutzen?
Liebe Grüße,
Nico

Hi!
I installed 3 instances of the Adapter and configured each with a different VIN-Number.
But all Instances are showing the same Data.
Any Chance to fix this?

Regards, 
Nico

**Comment by Newan** [comment]
Not tested with mutli instance. Pls send me an Test Account

**Comment by Newan** [comment]
Ich habe das nochmal getestet, also bei mir werden bei unterschiedlichen Instanzen auch andere Werte fürs Login gezogen.

Das einzige was ich mir vorstellen kann ist das alle Fahrzeuge in einem Account sind und diese immer wieder alle Fahrzeuge zurückgeben, ich aber immer nur das erste auswerte:

`vehicle = vehicles[0]; //is only one, because vin is in connection set`

Das ist nur zu klären wenn ich ein Account mit mehreren Fahrzeuge bekomme

**Comment by Newan** [comment]
keine Reaktion mehr, falls das Problem weiterhin existiert bitte neu eröffnen
